/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BadRequestResponse,
  InsightGroupEntry,
  InsightTotalEntry,
  InsightTransferEntry,
  InternalExceptionResponse,
  NotFoundResponse,
  UnauthenticatedResponse,
  ValidationErrorResponse,
} from '../models/index';
import {
    BadRequestResponseFromJSON,
    BadRequestResponseToJSON,
    InsightGroupEntryFromJSON,
    InsightGroupEntryToJSON,
    InsightTotalEntryFromJSON,
    InsightTotalEntryToJSON,
    InsightTransferEntryFromJSON,
    InsightTransferEntryToJSON,
    InternalExceptionResponseFromJSON,
    InternalExceptionResponseToJSON,
    NotFoundResponseFromJSON,
    NotFoundResponseToJSON,
    UnauthenticatedResponseFromJSON,
    UnauthenticatedResponseToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface InsightExpenseAssetRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightExpenseBillRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    bills?: Array<number>;
    accounts?: Array<number>;
}

export interface InsightExpenseBudgetRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    budgets?: Array<number>;
    accounts?: Array<number>;
}

export interface InsightExpenseCategoryRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    categories?: Array<number>;
    accounts?: Array<number>;
}

export interface InsightExpenseExpenseRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightExpenseNoBillRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightExpenseNoBudgetRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightExpenseNoCategoryRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightExpenseNoTagRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightExpenseTagRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    tags?: Array<number>;
    accounts?: Array<number>;
}

export interface InsightExpenseTotalRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightIncomeAssetRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightIncomeCategoryRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    categories?: Array<number>;
    accounts?: Array<number>;
}

export interface InsightIncomeNoCategoryRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightIncomeNoTagRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightIncomeRevenueRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightIncomeTagRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    tags?: Array<number>;
    accounts?: Array<number>;
}

export interface InsightIncomeTotalRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightTransferCategoryRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    categories?: Array<number>;
    accounts?: Array<number>;
}

export interface InsightTransferNoCategoryRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightTransferNoTagRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightTransferTagRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    tags?: Array<number>;
    accounts?: Array<number>;
}

export interface InsightTransferTotalRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

export interface InsightTransfersRequest {
    start: Date;
    end: Date;
    xTraceId?: string;
    accounts?: Array<number>;
}

/**
 * 
 */
export class InsightApi extends runtime.BaseAPI {

    /**
     * This endpoint gives a summary of the expenses made by the user, grouped by asset account. 
     * Insight into expenses, grouped by asset account.
     */
    async insightExpenseAssetRaw(requestParameters: InsightExpenseAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightGroupEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightExpenseAsset().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightExpenseAsset().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/expense/asset`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightGroupEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, grouped by asset account. 
     * Insight into expenses, grouped by asset account.
     */
    async insightExpenseAsset(requestParameters: InsightExpenseAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightGroupEntry>> {
        const response = await this.insightExpenseAssetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, grouped by (any) bill. 
     * Insight into expenses, grouped by bill.
     */
    async insightExpenseBillRaw(requestParameters: InsightExpenseBillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightGroupEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightExpenseBill().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightExpenseBill().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['bills'] != null) {
            queryParameters['bills[]'] = requestParameters['bills'];
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/expense/bill`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightGroupEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, grouped by (any) bill. 
     * Insight into expenses, grouped by bill.
     */
    async insightExpenseBill(requestParameters: InsightExpenseBillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightGroupEntry>> {
        const response = await this.insightExpenseBillRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, grouped by (any) budget. 
     * Insight into expenses, grouped by budget.
     */
    async insightExpenseBudgetRaw(requestParameters: InsightExpenseBudgetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightGroupEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightExpenseBudget().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightExpenseBudget().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['budgets'] != null) {
            queryParameters['budgets[]'] = requestParameters['budgets'];
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/expense/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightGroupEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, grouped by (any) budget. 
     * Insight into expenses, grouped by budget.
     */
    async insightExpenseBudget(requestParameters: InsightExpenseBudgetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightGroupEntry>> {
        const response = await this.insightExpenseBudgetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, grouped by (any) category. 
     * Insight into expenses, grouped by category.
     */
    async insightExpenseCategoryRaw(requestParameters: InsightExpenseCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightGroupEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightExpenseCategory().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightExpenseCategory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['categories'] != null) {
            queryParameters['categories[]'] = requestParameters['categories'];
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/expense/category`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightGroupEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, grouped by (any) category. 
     * Insight into expenses, grouped by category.
     */
    async insightExpenseCategory(requestParameters: InsightExpenseCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightGroupEntry>> {
        const response = await this.insightExpenseCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, grouped by expense account. 
     * Insight into expenses, grouped by expense account.
     */
    async insightExpenseExpenseRaw(requestParameters: InsightExpenseExpenseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightGroupEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightExpenseExpense().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightExpenseExpense().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/expense/expense`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightGroupEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, grouped by expense account. 
     * Insight into expenses, grouped by expense account.
     */
    async insightExpenseExpense(requestParameters: InsightExpenseExpenseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightGroupEntry>> {
        const response = await this.insightExpenseExpenseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, including only expenses with no bill. 
     * Insight into expenses, without bill.
     */
    async insightExpenseNoBillRaw(requestParameters: InsightExpenseNoBillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightTotalEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightExpenseNoBill().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightExpenseNoBill().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/expense/no-bill`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightTotalEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, including only expenses with no bill. 
     * Insight into expenses, without bill.
     */
    async insightExpenseNoBill(requestParameters: InsightExpenseNoBillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightTotalEntry>> {
        const response = await this.insightExpenseNoBillRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, including only expenses with no budget. 
     * Insight into expenses, without budget.
     */
    async insightExpenseNoBudgetRaw(requestParameters: InsightExpenseNoBudgetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightTotalEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightExpenseNoBudget().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightExpenseNoBudget().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/expense/no-budget`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightTotalEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, including only expenses with no budget. 
     * Insight into expenses, without budget.
     */
    async insightExpenseNoBudget(requestParameters: InsightExpenseNoBudgetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightTotalEntry>> {
        const response = await this.insightExpenseNoBudgetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, including only expenses with no category. 
     * Insight into expenses, without category.
     */
    async insightExpenseNoCategoryRaw(requestParameters: InsightExpenseNoCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightTotalEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightExpenseNoCategory().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightExpenseNoCategory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/expense/no-category`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightTotalEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, including only expenses with no category. 
     * Insight into expenses, without category.
     */
    async insightExpenseNoCategory(requestParameters: InsightExpenseNoCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightTotalEntry>> {
        const response = await this.insightExpenseNoCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, including only expenses with no tag. 
     * Insight into expenses, without tag.
     */
    async insightExpenseNoTagRaw(requestParameters: InsightExpenseNoTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightTotalEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightExpenseNoTag().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightExpenseNoTag().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/expense/no-tag`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightTotalEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, including only expenses with no tag. 
     * Insight into expenses, without tag.
     */
    async insightExpenseNoTag(requestParameters: InsightExpenseNoTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightTotalEntry>> {
        const response = await this.insightExpenseNoTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, grouped by (any) tag. 
     * Insight into expenses, grouped by tag.
     */
    async insightExpenseTagRaw(requestParameters: InsightExpenseTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightGroupEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightExpenseTag().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightExpenseTag().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags[]'] = requestParameters['tags'];
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/expense/tag`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightGroupEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the expenses made by the user, grouped by (any) tag. 
     * Insight into expenses, grouped by tag.
     */
    async insightExpenseTag(requestParameters: InsightExpenseTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightGroupEntry>> {
        const response = await this.insightExpenseTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a sum of the total expenses made by the user. 
     * Insight into total expenses.
     */
    async insightExpenseTotalRaw(requestParameters: InsightExpenseTotalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightTotalEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightExpenseTotal().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightExpenseTotal().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/expense/total`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightTotalEntryFromJSON));
    }

    /**
     * This endpoint gives a sum of the total expenses made by the user. 
     * Insight into total expenses.
     */
    async insightExpenseTotal(requestParameters: InsightExpenseTotalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightTotalEntry>> {
        const response = await this.insightExpenseTotalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the income received by the user, grouped by asset account. 
     * Insight into income, grouped by asset account.
     */
    async insightIncomeAssetRaw(requestParameters: InsightIncomeAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightGroupEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightIncomeAsset().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightIncomeAsset().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/income/asset`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightGroupEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the income received by the user, grouped by asset account. 
     * Insight into income, grouped by asset account.
     */
    async insightIncomeAsset(requestParameters: InsightIncomeAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightGroupEntry>> {
        const response = await this.insightIncomeAssetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the income received by the user, grouped by (any) category. 
     * Insight into income, grouped by category.
     */
    async insightIncomeCategoryRaw(requestParameters: InsightIncomeCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightGroupEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightIncomeCategory().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightIncomeCategory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['categories'] != null) {
            queryParameters['categories[]'] = requestParameters['categories'];
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/income/category`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightGroupEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the income received by the user, grouped by (any) category. 
     * Insight into income, grouped by category.
     */
    async insightIncomeCategory(requestParameters: InsightIncomeCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightGroupEntry>> {
        const response = await this.insightIncomeCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the income received by the user, including only income with no category. 
     * Insight into income, without category.
     */
    async insightIncomeNoCategoryRaw(requestParameters: InsightIncomeNoCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightTotalEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightIncomeNoCategory().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightIncomeNoCategory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/income/no-category`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightTotalEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the income received by the user, including only income with no category. 
     * Insight into income, without category.
     */
    async insightIncomeNoCategory(requestParameters: InsightIncomeNoCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightTotalEntry>> {
        const response = await this.insightIncomeNoCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the income received by the user, including only income with no tag. 
     * Insight into income, without tag.
     */
    async insightIncomeNoTagRaw(requestParameters: InsightIncomeNoTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightTotalEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightIncomeNoTag().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightIncomeNoTag().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/income/no-tag`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightTotalEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the income received by the user, including only income with no tag. 
     * Insight into income, without tag.
     */
    async insightIncomeNoTag(requestParameters: InsightIncomeNoTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightTotalEntry>> {
        const response = await this.insightIncomeNoTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the income received by the user, grouped by revenue account. 
     * Insight into income, grouped by revenue account.
     */
    async insightIncomeRevenueRaw(requestParameters: InsightIncomeRevenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightGroupEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightIncomeRevenue().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightIncomeRevenue().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/income/revenue`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightGroupEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the income received by the user, grouped by revenue account. 
     * Insight into income, grouped by revenue account.
     */
    async insightIncomeRevenue(requestParameters: InsightIncomeRevenueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightGroupEntry>> {
        const response = await this.insightIncomeRevenueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the income received by the user, grouped by (any) tag. 
     * Insight into income, grouped by tag.
     */
    async insightIncomeTagRaw(requestParameters: InsightIncomeTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightGroupEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightIncomeTag().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightIncomeTag().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags[]'] = requestParameters['tags'];
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/income/tag`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightGroupEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the income received by the user, grouped by (any) tag. 
     * Insight into income, grouped by tag.
     */
    async insightIncomeTag(requestParameters: InsightIncomeTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightGroupEntry>> {
        const response = await this.insightIncomeTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a sum of the total income received by the user. 
     * Insight into total income.
     */
    async insightIncomeTotalRaw(requestParameters: InsightIncomeTotalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightTotalEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightIncomeTotal().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightIncomeTotal().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/income/total`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightTotalEntryFromJSON));
    }

    /**
     * This endpoint gives a sum of the total income received by the user. 
     * Insight into total income.
     */
    async insightIncomeTotal(requestParameters: InsightIncomeTotalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightTotalEntry>> {
        const response = await this.insightIncomeTotalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the transfers made by the user, grouped by (any) category. 
     * Insight into transfers, grouped by category.
     */
    async insightTransferCategoryRaw(requestParameters: InsightTransferCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightGroupEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightTransferCategory().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightTransferCategory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['categories'] != null) {
            queryParameters['categories[]'] = requestParameters['categories'];
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/transfer/category`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightGroupEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the transfers made by the user, grouped by (any) category. 
     * Insight into transfers, grouped by category.
     */
    async insightTransferCategory(requestParameters: InsightTransferCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightGroupEntry>> {
        const response = await this.insightTransferCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the transfers made by the user, including only transfers with no category. 
     * Insight into transfers, without category.
     */
    async insightTransferNoCategoryRaw(requestParameters: InsightTransferNoCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightTotalEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightTransferNoCategory().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightTransferNoCategory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/transfer/no-category`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightTotalEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the transfers made by the user, including only transfers with no category. 
     * Insight into transfers, without category.
     */
    async insightTransferNoCategory(requestParameters: InsightTransferNoCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightTotalEntry>> {
        const response = await this.insightTransferNoCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the transfers made by the user, including only transfers with no tag. 
     * Insight into expenses, without tag.
     */
    async insightTransferNoTagRaw(requestParameters: InsightTransferNoTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightTotalEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightTransferNoTag().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightTransferNoTag().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/transfer/no-tag`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightTotalEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the transfers made by the user, including only transfers with no tag. 
     * Insight into expenses, without tag.
     */
    async insightTransferNoTag(requestParameters: InsightTransferNoTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightTotalEntry>> {
        const response = await this.insightTransferNoTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the transfers created by the user, grouped by (any) tag. 
     * Insight into transfers, grouped by tag.
     */
    async insightTransferTagRaw(requestParameters: InsightTransferTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightGroupEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightTransferTag().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightTransferTag().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags[]'] = requestParameters['tags'];
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/transfer/tag`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightGroupEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the transfers created by the user, grouped by (any) tag. 
     * Insight into transfers, grouped by tag.
     */
    async insightTransferTag(requestParameters: InsightTransferTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightGroupEntry>> {
        const response = await this.insightTransferTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a sum of the total amount transfers made by the user. 
     * Insight into total transfers.
     */
    async insightTransferTotalRaw(requestParameters: InsightTransferTotalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightTotalEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightTransferTotal().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightTransferTotal().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/transfer/total`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightTotalEntryFromJSON));
    }

    /**
     * This endpoint gives a sum of the total amount transfers made by the user. 
     * Insight into total transfers.
     */
    async insightTransferTotal(requestParameters: InsightTransferTotalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightTotalEntry>> {
        const response = await this.insightTransferTotalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint gives a summary of the transfers made by the user, grouped by asset account or lability. 
     * Insight into transfers, grouped by account.
     */
    async insightTransfersRaw(requestParameters: InsightTransfersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InsightTransferEntry>>> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling insightTransfers().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling insightTransfers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['accounts'] != null) {
            queryParameters['accounts[]'] = requestParameters['accounts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTraceId'] != null) {
            headerParameters['X-Trace-Id'] = String(requestParameters['xTraceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/insight/transfer/asset`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InsightTransferEntryFromJSON));
    }

    /**
     * This endpoint gives a summary of the transfers made by the user, grouped by asset account or lability. 
     * Insight into transfers, grouped by account.
     */
    async insightTransfers(requestParameters: InsightTransfersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InsightTransferEntry>> {
        const response = await this.insightTransfersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
