"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAccountArray = instanceOfAccountArray;
exports.AccountArrayFromJSON = AccountArrayFromJSON;
exports.AccountArrayFromJSONTyped = AccountArrayFromJSONTyped;
exports.AccountArrayToJSON = AccountArrayToJSON;
exports.AccountArrayToJSONTyped = AccountArrayToJSONTyped;
const Meta_1 = require("./Meta");
const AccountRead_1 = require("./AccountRead");
/**
 * Check if a given object implements the AccountArray interface.
 */
function instanceOfAccountArray(value) {
    if (!('data' in value) || value['data'] === undefined)
        return false;
    if (!('meta' in value) || value['meta'] === undefined)
        return false;
    return true;
}
function AccountArrayFromJSON(json) {
    return AccountArrayFromJSONTyped(json, false);
}
function AccountArrayFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'data': (json['data'].map(AccountRead_1.AccountReadFromJSON)),
        'meta': (0, Meta_1.MetaFromJSON)(json['meta']),
    };
}
function AccountArrayToJSON(json) {
    return AccountArrayToJSONTyped(json, false);
}
function AccountArrayToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'data': (value['data'].map(AccountRead_1.AccountReadToJSON)),
        'meta': (0, Meta_1.MetaToJSON)(value['meta']),
    };
}
