/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { AttachmentRead } from './AttachmentRead';
import {
    AttachmentReadFromJSON,
    AttachmentReadFromJSONTyped,
    AttachmentReadToJSON,
    AttachmentReadToJSONTyped,
} from './AttachmentRead';

/**
 * 
 * @export
 * @interface AttachmentArray
 */
export interface AttachmentArray {
    /**
     * 
     * @type {Array<AttachmentRead>}
     * @memberof AttachmentArray
     */
    data: Array<AttachmentRead>;
    /**
     * 
     * @type {Meta}
     * @memberof AttachmentArray
     */
    meta: Meta;
}

/**
 * Check if a given object implements the AttachmentArray interface.
 */
export function instanceOfAttachmentArray(value: object): value is AttachmentArray {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function AttachmentArrayFromJSON(json: any): AttachmentArray {
    return AttachmentArrayFromJSONTyped(json, false);
}

export function AttachmentArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentArray {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AttachmentReadFromJSON)),
        'meta': MetaFromJSON(json['meta']),
    };
}

export function AttachmentArrayToJSON(json: any): AttachmentArray {
    return AttachmentArrayToJSONTyped(json, false);
}

export function AttachmentArrayToJSONTyped(value?: AttachmentArray | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(AttachmentReadToJSON)),
        'meta': MetaToJSON(value['meta']),
    };
}

