/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Period for the auto budget
 * @export
 */
export const AutoBudgetPeriod = {
    Daily: 'daily',
    Weekly: 'weekly',
    Monthly: 'monthly',
    Quarterly: 'quarterly',
    HalfYear: 'half-year',
    Yearly: 'yearly'
} as const;
export type AutoBudgetPeriod = typeof AutoBudgetPeriod[keyof typeof AutoBudgetPeriod];


export function instanceOfAutoBudgetPeriod(value: any): boolean {
    for (const key in AutoBudgetPeriod) {
        if (Object.prototype.hasOwnProperty.call(AutoBudgetPeriod, key)) {
            if (AutoBudgetPeriod[key as keyof typeof AutoBudgetPeriod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AutoBudgetPeriodFromJSON(json: any): AutoBudgetPeriod {
    return AutoBudgetPeriodFromJSONTyped(json, false);
}

export function AutoBudgetPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoBudgetPeriod {
    return json as AutoBudgetPeriod;
}

export function AutoBudgetPeriodToJSON(value?: AutoBudgetPeriod | null): any {
    return value as any;
}

export function AutoBudgetPeriodToJSONTyped(value: any, ignoreDiscriminator: boolean): AutoBudgetPeriod {
    return value as AutoBudgetPeriod;
}

