/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutocompleteTransaction
 */
export interface AutocompleteTransaction {
    /**
     * The ID of a transaction journal (basically a single split).
     * @type {string}
     * @memberof AutocompleteTransaction
     */
    id: string;
    /**
     * The ID of the underlying transaction group.
     * @type {string}
     * @memberof AutocompleteTransaction
     */
    transactionGroupId?: string;
    /**
     * Transaction description
     * @type {string}
     * @memberof AutocompleteTransaction
     */
    name: string;
    /**
     * Transaction description
     * @type {string}
     * @memberof AutocompleteTransaction
     */
    description: string;
}

/**
 * Check if a given object implements the AutocompleteTransaction interface.
 */
export function instanceOfAutocompleteTransaction(value: object): value is AutocompleteTransaction {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function AutocompleteTransactionFromJSON(json: any): AutocompleteTransaction {
    return AutocompleteTransactionFromJSONTyped(json, false);
}

export function AutocompleteTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'transactionGroupId': json['transaction_group_id'] == null ? undefined : json['transaction_group_id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function AutocompleteTransactionToJSON(json: any): AutocompleteTransaction {
    return AutocompleteTransactionToJSONTyped(json, false);
}

export function AutocompleteTransactionToJSONTyped(value?: AutocompleteTransaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'transaction_group_id': value['transactionGroupId'],
        'name': value['name'],
        'description': value['description'],
    };
}

