"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAvailableBudgetRead = instanceOfAvailableBudgetRead;
exports.AvailableBudgetReadFromJSON = AvailableBudgetReadFromJSON;
exports.AvailableBudgetReadFromJSONTyped = AvailableBudgetReadFromJSONTyped;
exports.AvailableBudgetReadToJSON = AvailableBudgetReadToJSON;
exports.AvailableBudgetReadToJSONTyped = AvailableBudgetReadToJSONTyped;
const AvailableBudget_1 = require("./AvailableBudget");
/**
 * Check if a given object implements the AvailableBudgetRead interface.
 */
function instanceOfAvailableBudgetRead(value) {
    if (!('type' in value) || value['type'] === undefined)
        return false;
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('attributes' in value) || value['attributes'] === undefined)
        return false;
    return true;
}
function AvailableBudgetReadFromJSON(json) {
    return AvailableBudgetReadFromJSONTyped(json, false);
}
function AvailableBudgetReadFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'type': json['type'],
        'id': json['id'],
        'attributes': (0, AvailableBudget_1.AvailableBudgetFromJSON)(json['attributes']),
    };
}
function AvailableBudgetReadToJSON(json) {
    return AvailableBudgetReadToJSONTyped(json, false);
}
function AvailableBudgetReadToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'type': value['type'],
        'id': value['id'],
        'attributes': (0, AvailableBudget_1.AvailableBudgetToJSON)(value['attributes']),
    };
}
