/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BillRepeatFrequency } from './BillRepeatFrequency';
import {
    BillRepeatFrequencyFromJSON,
    BillRepeatFrequencyFromJSONTyped,
    BillRepeatFrequencyToJSON,
    BillRepeatFrequencyToJSONTyped,
} from './BillRepeatFrequency';

/**
 * 
 * @export
 * @interface BillStore
 */
export interface BillStore {
    /**
     * Use either currency_id or currency_code
     * @type {string}
     * @memberof BillStore
     */
    currencyId?: string;
    /**
     * Use either currency_id or currency_code
     * @type {string}
     * @memberof BillStore
     */
    currencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BillStore
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BillStore
     */
    amountMin: string;
    /**
     * 
     * @type {string}
     * @memberof BillStore
     */
    amountMax: string;
    /**
     * 
     * @type {Date}
     * @memberof BillStore
     */
    date: Date;
    /**
     * The date after which this bill is no longer valid or applicable
     * @type {Date}
     * @memberof BillStore
     */
    endDate?: Date;
    /**
     * The date before which the bill must be renewed (or cancelled)
     * @type {Date}
     * @memberof BillStore
     */
    extensionDate?: Date;
    /**
     * 
     * @type {BillRepeatFrequency}
     * @memberof BillStore
     */
    repeatFreq: BillRepeatFrequency;
    /**
     * How often the bill must be skipped. 1 means a bi-monthly bill.
     * @type {number}
     * @memberof BillStore
     */
    skip?: number;
    /**
     * If the bill is active.
     * @type {boolean}
     * @memberof BillStore
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BillStore
     */
    notes?: string | null;
    /**
     * The group ID of the group this object is part of. NULL if no group.
     * @type {string}
     * @memberof BillStore
     */
    objectGroupId?: string | null;
    /**
     * The name of the group. NULL if no group.
     * @type {string}
     * @memberof BillStore
     */
    objectGroupTitle?: string | null;
}



/**
 * Check if a given object implements the BillStore interface.
 */
export function instanceOfBillStore(value: object): value is BillStore {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('amountMin' in value) || value['amountMin'] === undefined) return false;
    if (!('amountMax' in value) || value['amountMax'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('repeatFreq' in value) || value['repeatFreq'] === undefined) return false;
    return true;
}

export function BillStoreFromJSON(json: any): BillStore {
    return BillStoreFromJSONTyped(json, false);
}

export function BillStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillStore {
    if (json == null) {
        return json;
    }
    return {
        
        'currencyId': json['currency_id'] == null ? undefined : json['currency_id'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
        'name': json['name'],
        'amountMin': json['amount_min'],
        'amountMax': json['amount_max'],
        'date': (new Date(json['date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'extensionDate': json['extension_date'] == null ? undefined : (new Date(json['extension_date'])),
        'repeatFreq': BillRepeatFrequencyFromJSON(json['repeat_freq']),
        'skip': json['skip'] == null ? undefined : json['skip'],
        'active': json['active'] == null ? undefined : json['active'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'objectGroupId': json['object_group_id'] == null ? undefined : json['object_group_id'],
        'objectGroupTitle': json['object_group_title'] == null ? undefined : json['object_group_title'],
    };
}

export function BillStoreToJSON(json: any): BillStore {
    return BillStoreToJSONTyped(json, false);
}

export function BillStoreToJSONTyped(value?: BillStore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency_id': value['currencyId'],
        'currency_code': value['currencyCode'],
        'name': value['name'],
        'amount_min': value['amountMin'],
        'amount_max': value['amountMax'],
        'date': ((value['date']).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
        'extension_date': value['extensionDate'] == null ? undefined : ((value['extensionDate']).toISOString()),
        'repeat_freq': BillRepeatFrequencyToJSON(value['repeatFreq']),
        'skip': value['skip'],
        'active': value['active'],
        'notes': value['notes'],
        'object_group_id': value['objectGroupId'],
        'object_group_title': value['objectGroupTitle'],
    };
}

