/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { BudgetRead } from './BudgetRead';
import {
    BudgetReadFromJSON,
    BudgetReadFromJSONTyped,
    BudgetReadToJSON,
    BudgetReadToJSONTyped,
} from './BudgetRead';

/**
 * 
 * @export
 * @interface BudgetArray
 */
export interface BudgetArray {
    /**
     * 
     * @type {Array<BudgetRead>}
     * @memberof BudgetArray
     */
    data: Array<BudgetRead>;
    /**
     * 
     * @type {Meta}
     * @memberof BudgetArray
     */
    meta: Meta;
}

/**
 * Check if a given object implements the BudgetArray interface.
 */
export function instanceOfBudgetArray(value: object): value is BudgetArray {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function BudgetArrayFromJSON(json: any): BudgetArray {
    return BudgetArrayFromJSONTyped(json, false);
}

export function BudgetArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetArray {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(BudgetReadFromJSON)),
        'meta': MetaFromJSON(json['meta']),
    };
}

export function BudgetArrayToJSON(json: any): BudgetArray {
    return BudgetArrayToJSONTyped(json, false);
}

export function BudgetArrayToJSONTyped(value?: BudgetArray | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(BudgetReadToJSON)),
        'meta': MetaToJSON(value['meta']),
    };
}

