"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfBudgetStore = instanceOfBudgetStore;
exports.BudgetStoreFromJSON = BudgetStoreFromJSON;
exports.BudgetStoreFromJSONTyped = BudgetStoreFromJSONTyped;
exports.BudgetStoreToJSON = BudgetStoreToJSON;
exports.BudgetStoreToJSONTyped = BudgetStoreToJSONTyped;
const AutoBudgetType_1 = require("./AutoBudgetType");
const AutoBudgetPeriod_1 = require("./AutoBudgetPeriod");
/**
 * Check if a given object implements the BudgetStore interface.
 */
function instanceOfBudgetStore(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    return true;
}
function BudgetStoreFromJSON(json) {
    return BudgetStoreFromJSONTyped(json, false);
}
function BudgetStoreFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'],
        'active': json['active'] == null ? undefined : json['active'],
        'order': json['order'] == null ? undefined : json['order'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'autoBudgetType': json['auto_budget_type'] == null ? undefined : (0, AutoBudgetType_1.AutoBudgetTypeFromJSON)(json['auto_budget_type']),
        'autoBudgetCurrencyId': json['auto_budget_currency_id'] == null ? undefined : json['auto_budget_currency_id'],
        'autoBudgetCurrencyCode': json['auto_budget_currency_code'] == null ? undefined : json['auto_budget_currency_code'],
        'autoBudgetAmount': json['auto_budget_amount'] == null ? undefined : json['auto_budget_amount'],
        'autoBudgetPeriod': json['auto_budget_period'] == null ? undefined : (0, AutoBudgetPeriod_1.AutoBudgetPeriodFromJSON)(json['auto_budget_period']),
    };
}
function BudgetStoreToJSON(json) {
    return BudgetStoreToJSONTyped(json, false);
}
function BudgetStoreToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'active': value['active'],
        'notes': value['notes'],
        'auto_budget_type': (0, AutoBudgetType_1.AutoBudgetTypeToJSON)(value['autoBudgetType']),
        'auto_budget_currency_id': value['autoBudgetCurrencyId'],
        'auto_budget_currency_code': value['autoBudgetCurrencyCode'],
        'auto_budget_amount': value['autoBudgetAmount'],
        'auto_budget_period': (0, AutoBudgetPeriod_1.AutoBudgetPeriodToJSON)(value['autoBudgetPeriod']),
    };
}
