"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfBudgetLimit = instanceOfBudgetLimit;
exports.BudgetLimitFromJSON = BudgetLimitFromJSON;
exports.BudgetLimitFromJSONTyped = BudgetLimitFromJSONTyped;
exports.BudgetLimitToJSON = BudgetLimitToJSON;
exports.BudgetLimitToJSONTyped = BudgetLimitToJSONTyped;
/**
 * Check if a given object implements the BudgetLimit interface.
 */
function instanceOfBudgetLimit(value) {
    if (!('start' in value) || value['start'] === undefined)
        return false;
    if (!('end' in value) || value['end'] === undefined)
        return false;
    if (!('budgetId' in value) || value['budgetId'] === undefined)
        return false;
    if (!('amount' in value) || value['amount'] === undefined)
        return false;
    return true;
}
function BudgetLimitFromJSON(json) {
    return BudgetLimitFromJSONTyped(json, false);
}
function BudgetLimitFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'currencyId': json['currency_id'] == null ? undefined : json['currency_id'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
        'currencyName': json['currency_name'] == null ? undefined : json['currency_name'],
        'currencySymbol': json['currency_symbol'] == null ? undefined : json['currency_symbol'],
        'currencyDecimalPlaces': json['currency_decimal_places'] == null ? undefined : json['currency_decimal_places'],
        'nativeCurrencyId': json['native_currency_id'] == null ? undefined : json['native_currency_id'],
        'nativeCurrencyCode': json['native_currency_code'] == null ? undefined : json['native_currency_code'],
        'nativeCurrencySymbol': json['native_currency_symbol'] == null ? undefined : json['native_currency_symbol'],
        'nativeCurrencyDecimalPlaces': json['native_currency_decimal_places'] == null ? undefined : json['native_currency_decimal_places'],
        'budgetId': json['budget_id'],
        'period': json['period'] == null ? undefined : json['period'],
        'amount': json['amount'],
        'nativeAmount': json['native_amount'] == null ? undefined : json['native_amount'],
        'spent': json['spent'] == null ? undefined : json['spent'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}
function BudgetLimitToJSON(json) {
    return BudgetLimitToJSONTyped(json, false);
}
function BudgetLimitToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'currency_id': value['currencyId'],
        'currency_code': value['currencyCode'],
        'amount': value['amount'],
        'notes': value['notes'],
    };
}
