"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfBudgetLimitStore = instanceOfBudgetLimitStore;
exports.BudgetLimitStoreFromJSON = BudgetLimitStoreFromJSON;
exports.BudgetLimitStoreFromJSONTyped = BudgetLimitStoreFromJSONTyped;
exports.BudgetLimitStoreToJSON = BudgetLimitStoreToJSON;
exports.BudgetLimitStoreToJSONTyped = BudgetLimitStoreToJSONTyped;
/**
 * Check if a given object implements the BudgetLimitStore interface.
 */
function instanceOfBudgetLimitStore(value) {
    if (!('budgetId' in value) || value['budgetId'] === undefined)
        return false;
    if (!('start' in value) || value['start'] === undefined)
        return false;
    if (!('end' in value) || value['end'] === undefined)
        return false;
    if (!('amount' in value) || value['amount'] === undefined)
        return false;
    return true;
}
function BudgetLimitStoreFromJSON(json) {
    return BudgetLimitStoreFromJSONTyped(json, false);
}
function BudgetLimitStoreFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'currencyId': json['currency_id'] == null ? undefined : json['currency_id'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
        'budgetId': json['budget_id'],
        'start': (new Date(json['start'])),
        'period': json['period'] == null ? undefined : json['period'],
        'end': (new Date(json['end'])),
        'amount': json['amount'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}
function BudgetLimitStoreToJSON(json) {
    return BudgetLimitStoreToJSONTyped(json, false);
}
function BudgetLimitStoreToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'currency_id': value['currencyId'],
        'currency_code': value['currencyCode'],
        'start': ((value['start']).toISOString().substring(0, 10)),
        'end': ((value['end']).toISOString().substring(0, 10)),
        'amount': value['amount'],
        'notes': value['notes'],
    };
}
