/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BudgetLimit
 */
export interface BudgetLimit {
    /**
     * 
     * @type {Date}
     * @memberof BudgetLimit
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BudgetLimit
     */
    readonly updatedAt?: Date;
    /**
     * Start date of the budget limit.
     * @type {Date}
     * @memberof BudgetLimit
     */
    start: Date;
    /**
     * End date of the budget limit.
     * @type {Date}
     * @memberof BudgetLimit
     */
    end: Date;
    /**
     * Use either currency_id or currency_code. Defaults to the user's default currency.
     * @type {string}
     * @memberof BudgetLimit
     */
    currencyId?: string;
    /**
     * Use either currency_id or currency_code. Defaults to the user's default currency.
     * @type {string}
     * @memberof BudgetLimit
     */
    currencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BudgetLimit
     */
    readonly currencyName?: string;
    /**
     * 
     * @type {string}
     * @memberof BudgetLimit
     */
    readonly currencySymbol?: string;
    /**
     * 
     * @type {number}
     * @memberof BudgetLimit
     */
    readonly currencyDecimalPlaces?: number;
    /**
     * The administration's native currency ID.
     * @type {string}
     * @memberof BudgetLimit
     */
    readonly nativeCurrencyId?: string;
    /**
     * The administration's native currency code.
     * @type {string}
     * @memberof BudgetLimit
     */
    readonly nativeCurrencyCode?: string;
    /**
     * The administration's native currency symbol.
     * @type {string}
     * @memberof BudgetLimit
     */
    readonly nativeCurrencySymbol?: string;
    /**
     * The administration's native currency decimal places.
     * @type {number}
     * @memberof BudgetLimit
     */
    readonly nativeCurrencyDecimalPlaces?: number;
    /**
     * The budget ID of the associated budget.
     * @type {string}
     * @memberof BudgetLimit
     */
    readonly budgetId: string;
    /**
     * Period of the budget limit. Only used when auto-generated by auto-budget.
     * @type {string}
     * @memberof BudgetLimit
     */
    readonly period?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BudgetLimit
     */
    amount: string;
    /**
     * The amount of this budget limit in the user's native currency, if the original amount is in a different currency.
     * @type {string}
     * @memberof BudgetLimit
     */
    readonly nativeAmount?: string | null;
    /**
     * Will be in the native currency if this is turned on by the user.
     * @type {string}
     * @memberof BudgetLimit
     */
    readonly spent?: string | null;
    /**
     * Some notes for this specific budget limit.
     * @type {string}
     * @memberof BudgetLimit
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the BudgetLimit interface.
 */
export function instanceOfBudgetLimit(value: object): value is BudgetLimit {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('budgetId' in value) || value['budgetId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function BudgetLimitFromJSON(json: any): BudgetLimit {
    return BudgetLimitFromJSONTyped(json, false);
}

export function BudgetLimitFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetLimit {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'currencyId': json['currency_id'] == null ? undefined : json['currency_id'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
        'currencyName': json['currency_name'] == null ? undefined : json['currency_name'],
        'currencySymbol': json['currency_symbol'] == null ? undefined : json['currency_symbol'],
        'currencyDecimalPlaces': json['currency_decimal_places'] == null ? undefined : json['currency_decimal_places'],
        'nativeCurrencyId': json['native_currency_id'] == null ? undefined : json['native_currency_id'],
        'nativeCurrencyCode': json['native_currency_code'] == null ? undefined : json['native_currency_code'],
        'nativeCurrencySymbol': json['native_currency_symbol'] == null ? undefined : json['native_currency_symbol'],
        'nativeCurrencyDecimalPlaces': json['native_currency_decimal_places'] == null ? undefined : json['native_currency_decimal_places'],
        'budgetId': json['budget_id'],
        'period': json['period'] == null ? undefined : json['period'],
        'amount': json['amount'],
        'nativeAmount': json['native_amount'] == null ? undefined : json['native_amount'],
        'spent': json['spent'] == null ? undefined : json['spent'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function BudgetLimitToJSON(json: any): BudgetLimit {
    return BudgetLimitToJSONTyped(json, false);
}

export function BudgetLimitToJSONTyped(value?: Omit<BudgetLimit, 'created_at'|'updated_at'|'currency_name'|'currency_symbol'|'currency_decimal_places'|'native_currency_id'|'native_currency_code'|'native_currency_symbol'|'native_currency_decimal_places'|'budget_id'|'period'|'native_amount'|'spent'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'currency_id': value['currencyId'],
        'currency_code': value['currencyCode'],
        'amount': value['amount'],
        'notes': value['notes'],
    };
}

