/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BudgetSpent
 */
export interface BudgetSpent {
    /**
     * The amount spent. This is in the administration's native currency, if the conversion is turned on.
     * @type {string}
     * @memberof BudgetSpent
     */
    sum?: string;
    /**
     * 
     * @type {string}
     * @memberof BudgetSpent
     */
    currencyId?: string;
    /**
     * 
     * @type {string}
     * @memberof BudgetSpent
     */
    currencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BudgetSpent
     */
    currencySymbol?: string;
    /**
     * Number of decimals supported by the currency
     * @type {number}
     * @memberof BudgetSpent
     */
    currencyDecimalPlaces?: number;
}

/**
 * Check if a given object implements the BudgetSpent interface.
 */
export function instanceOfBudgetSpent(value: object): value is BudgetSpent {
    return true;
}

export function BudgetSpentFromJSON(json: any): BudgetSpent {
    return BudgetSpentFromJSONTyped(json, false);
}

export function BudgetSpentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetSpent {
    if (json == null) {
        return json;
    }
    return {
        
        'sum': json['sum'] == null ? undefined : json['sum'],
        'currencyId': json['currency_id'] == null ? undefined : json['currency_id'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
        'currencySymbol': json['currency_symbol'] == null ? undefined : json['currency_symbol'],
        'currencyDecimalPlaces': json['currency_decimal_places'] == null ? undefined : json['currency_decimal_places'],
    };
}

export function BudgetSpentToJSON(json: any): BudgetSpent {
    return BudgetSpentToJSONTyped(json, false);
}

export function BudgetSpentToJSONTyped(value?: BudgetSpent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sum': value['sum'],
        'currency_id': value['currencyId'],
        'currency_code': value['currencyCode'],
        'currency_symbol': value['currencySymbol'],
        'currency_decimal_places': value['currencyDecimalPlaces'],
    };
}

