/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryEarned
 */
export interface CategoryEarned {
    /**
     * 
     * @type {string}
     * @memberof CategoryEarned
     */
    currencyId?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryEarned
     */
    currencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryEarned
     */
    currencySymbol?: string;
    /**
     * Number of decimals supported by the currency
     * @type {number}
     * @memberof CategoryEarned
     */
    currencyDecimalPlaces?: number;
    /**
     * The amount earned.
     * @type {string}
     * @memberof CategoryEarned
     */
    sum?: string;
}

/**
 * Check if a given object implements the CategoryEarned interface.
 */
export function instanceOfCategoryEarned(value: object): value is CategoryEarned {
    return true;
}

export function CategoryEarnedFromJSON(json: any): CategoryEarned {
    return CategoryEarnedFromJSONTyped(json, false);
}

export function CategoryEarnedFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryEarned {
    if (json == null) {
        return json;
    }
    return {
        
        'currencyId': json['currency_id'] == null ? undefined : json['currency_id'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
        'currencySymbol': json['currency_symbol'] == null ? undefined : json['currency_symbol'],
        'currencyDecimalPlaces': json['currency_decimal_places'] == null ? undefined : json['currency_decimal_places'],
        'sum': json['sum'] == null ? undefined : json['sum'],
    };
}

export function CategoryEarnedToJSON(json: any): CategoryEarned {
    return CategoryEarnedToJSONTyped(json, false);
}

export function CategoryEarnedToJSONTyped(value?: CategoryEarned | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency_id': value['currencyId'],
        'currency_code': value['currencyCode'],
        'currency_symbol': value['currencySymbol'],
        'currency_decimal_places': value['currencyDecimalPlaces'],
        'sum': value['sum'],
    };
}

