"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfCategoryRead = instanceOfCategoryRead;
exports.CategoryReadFromJSON = CategoryReadFromJSON;
exports.CategoryReadFromJSONTyped = CategoryReadFromJSONTyped;
exports.CategoryReadToJSON = CategoryReadToJSON;
exports.CategoryReadToJSONTyped = CategoryReadToJSONTyped;
const Category_1 = require("./Category");
/**
 * Check if a given object implements the CategoryRead interface.
 */
function instanceOfCategoryRead(value) {
    if (!('type' in value) || value['type'] === undefined)
        return false;
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('attributes' in value) || value['attributes'] === undefined)
        return false;
    return true;
}
function CategoryReadFromJSON(json) {
    return CategoryReadFromJSONTyped(json, false);
}
function CategoryReadFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'type': json['type'],
        'id': json['id'],
        'attributes': (0, Category_1.CategoryFromJSON)(json['attributes']),
    };
}
function CategoryReadToJSON(json) {
    return CategoryReadToJSONTyped(json, false);
}
function CategoryReadToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'type': value['type'],
        'id': value['id'],
        'attributes': (0, Category_1.CategoryToJSON)(value['attributes']),
    };
}
