"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfCategory = instanceOfCategory;
exports.CategoryFromJSON = CategoryFromJSON;
exports.CategoryFromJSONTyped = CategoryFromJSONTyped;
exports.CategoryToJSON = CategoryToJSON;
exports.CategoryToJSONTyped = CategoryToJSONTyped;
const CategoryEarned_1 = require("./CategoryEarned");
const CategorySpent_1 = require("./CategorySpent");
/**
 * Check if a given object implements the Category interface.
 */
function instanceOfCategory(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    return true;
}
function CategoryFromJSON(json) {
    return CategoryFromJSONTyped(json, false);
}
function CategoryFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'name': json['name'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'nativeCurrencyId': json['native_currency_id'] == null ? undefined : json['native_currency_id'],
        'nativeCurrencyCode': json['native_currency_code'] == null ? undefined : json['native_currency_code'],
        'nativeCurrencySymbol': json['native_currency_symbol'] == null ? undefined : json['native_currency_symbol'],
        'nativeCurrencyDecimalPlaces': json['native_currency_decimal_places'] == null ? undefined : json['native_currency_decimal_places'],
        'spent': json['spent'] == null ? undefined : (json['spent'].map(CategorySpent_1.CategorySpentFromJSON)),
        'earned': json['earned'] == null ? undefined : (json['earned'].map(CategoryEarned_1.CategoryEarnedFromJSON)),
    };
}
function CategoryToJSON(json) {
    return CategoryToJSONTyped(json, false);
}
function CategoryToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'notes': value['notes'],
    };
}
