/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChartDataPoint
 */
export interface ChartDataPoint {
    /**
     * The key is the label of the value, so for example: '2018-01-01' => 13 or 'Groceries' => -123.
     * @type {string}
     * @memberof ChartDataPoint
     */
    key?: string;
}

/**
 * Check if a given object implements the ChartDataPoint interface.
 */
export function instanceOfChartDataPoint(value: object): value is ChartDataPoint {
    return true;
}

export function ChartDataPointFromJSON(json: any): ChartDataPoint {
    return ChartDataPointFromJSONTyped(json, false);
}

export function ChartDataPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChartDataPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function ChartDataPointToJSON(json: any): ChartDataPoint {
    return ChartDataPointToJSONTyped(json, false);
}

export function ChartDataPointToJSONTyped(value?: ChartDataPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
    };
}

