"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfConfigurationUpdate = instanceOfConfigurationUpdate;
exports.ConfigurationUpdateFromJSON = ConfigurationUpdateFromJSON;
exports.ConfigurationUpdateFromJSONTyped = ConfigurationUpdateFromJSONTyped;
exports.ConfigurationUpdateToJSON = ConfigurationUpdateToJSON;
exports.ConfigurationUpdateToJSONTyped = ConfigurationUpdateToJSONTyped;
const PolymorphicProperty_1 = require("./PolymorphicProperty");
/**
 * Check if a given object implements the ConfigurationUpdate interface.
 */
function instanceOfConfigurationUpdate(value) {
    if (!('value' in value) || value['value'] === undefined)
        return false;
    return true;
}
function ConfigurationUpdateFromJSON(json) {
    return ConfigurationUpdateFromJSONTyped(json, false);
}
function ConfigurationUpdateFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'value': (0, PolymorphicProperty_1.PolymorphicPropertyFromJSON)(json['value']),
    };
}
function ConfigurationUpdateToJSON(json) {
    return ConfigurationUpdateToJSONTyped(json, false);
}
function ConfigurationUpdateToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'value': (0, PolymorphicProperty_1.PolymorphicPropertyToJSON)(value['value']),
    };
}
