"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConfigValueUpdateFilter = void 0;
exports.instanceOfConfigValueUpdateFilter = instanceOfConfigValueUpdateFilter;
exports.ConfigValueUpdateFilterFromJSON = ConfigValueUpdateFilterFromJSON;
exports.ConfigValueUpdateFilterFromJSONTyped = ConfigValueUpdateFilterFromJSONTyped;
exports.ConfigValueUpdateFilterToJSON = ConfigValueUpdateFilterToJSON;
exports.ConfigValueUpdateFilterToJSONTyped = ConfigValueUpdateFilterToJSONTyped;
/**
 *
 * @export
 */
exports.ConfigValueUpdateFilter = {
    ConfigurationIsDemoSite: 'configuration.is_demo_site',
    ConfigurationPermissionUpdateCheck: 'configuration.permission_update_check',
    ConfigurationLastUpdateCheck: 'configuration.last_update_check',
    ConfigurationSingleUserMode: 'configuration.single_user_mode'
};
function instanceOfConfigValueUpdateFilter(value) {
    for (const key in exports.ConfigValueUpdateFilter) {
        if (Object.prototype.hasOwnProperty.call(exports.ConfigValueUpdateFilter, key)) {
            if (exports.ConfigValueUpdateFilter[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function ConfigValueUpdateFilterFromJSON(json) {
    return ConfigValueUpdateFilterFromJSONTyped(json, false);
}
function ConfigValueUpdateFilterFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function ConfigValueUpdateFilterToJSON(value) {
    return value;
}
function ConfigValueUpdateFilterToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
