"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfInsightTransferEntry = instanceOfInsightTransferEntry;
exports.InsightTransferEntryFromJSON = InsightTransferEntryFromJSON;
exports.InsightTransferEntryFromJSONTyped = InsightTransferEntryFromJSONTyped;
exports.InsightTransferEntryToJSON = InsightTransferEntryToJSON;
exports.InsightTransferEntryToJSONTyped = InsightTransferEntryToJSONTyped;
/**
 * Check if a given object implements the InsightTransferEntry interface.
 */
function instanceOfInsightTransferEntry(value) {
    return true;
}
function InsightTransferEntryFromJSON(json) {
    return InsightTransferEntryFromJSONTyped(json, false);
}
function InsightTransferEntryFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'difference': json['difference'] == null ? undefined : json['difference'],
        'differenceFloat': json['difference_float'] == null ? undefined : json['difference_float'],
        '_in': json['in'] == null ? undefined : json['in'],
        'inFloat': json['in_float'] == null ? undefined : json['in_float'],
        'out': json['out'] == null ? undefined : json['out'],
        'outFloat': json['out_float'] == null ? undefined : json['out_float'],
        'currencyId': json['currency_id'] == null ? undefined : json['currency_id'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
    };
}
function InsightTransferEntryToJSON(json) {
    return InsightTransferEntryToJSONTyped(json, false);
}
function InsightTransferEntryToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'difference': value['difference'],
        'difference_float': value['differenceFloat'],
        'in': value['_in'],
        'in_float': value['inFloat'],
        'out': value['out'],
        'out_float': value['outFloat'],
        'currency_id': value['currencyId'],
        'currency_code': value['currencyCode'],
    };
}
