/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Mandatory when type is liability. Period over which the interest is calculated.
 * @export
 */
export const InterestPeriodProperty = {
    Weekly: 'weekly',
    Monthly: 'monthly',
    Quarterly: 'quarterly',
    HalfYear: 'half-year',
    Yearly: 'yearly'
} as const;
export type InterestPeriodProperty = typeof InterestPeriodProperty[keyof typeof InterestPeriodProperty];


export function instanceOfInterestPeriodProperty(value: any): boolean {
    for (const key in InterestPeriodProperty) {
        if (Object.prototype.hasOwnProperty.call(InterestPeriodProperty, key)) {
            if (InterestPeriodProperty[key as keyof typeof InterestPeriodProperty] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InterestPeriodPropertyFromJSON(json: any): InterestPeriodProperty {
    return InterestPeriodPropertyFromJSONTyped(json, false);
}

export function InterestPeriodPropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterestPeriodProperty {
    return json as InterestPeriodProperty;
}

export function InterestPeriodPropertyToJSON(value?: InterestPeriodProperty | null): any {
    return value as any;
}

export function InterestPeriodPropertyToJSONTyped(value: any, ignoreDiscriminator: boolean): InterestPeriodProperty {
    return value as InterestPeriodProperty;
}

