/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalExceptionResponse
 */
export interface InternalExceptionResponse {
    /**
     * 
     * @type {string}
     * @memberof InternalExceptionResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalExceptionResponse
     */
    exception?: string;
}

/**
 * Check if a given object implements the InternalExceptionResponse interface.
 */
export function instanceOfInternalExceptionResponse(value: object): value is InternalExceptionResponse {
    return true;
}

export function InternalExceptionResponseFromJSON(json: any): InternalExceptionResponse {
    return InternalExceptionResponseFromJSONTyped(json, false);
}

export function InternalExceptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalExceptionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'exception': json['exception'] == null ? undefined : json['exception'],
    };
}

export function InternalExceptionResponseToJSON(json: any): InternalExceptionResponse {
    return InternalExceptionResponseToJSONTyped(json, false);
}

export function InternalExceptionResponseToJSONTyped(value?: InternalExceptionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'exception': value['exception'],
    };
}

