/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LinkTypeRead } from './LinkTypeRead';
import {
    LinkTypeReadFromJSON,
    LinkTypeReadFromJSONTyped,
    LinkTypeReadToJSON,
    LinkTypeReadToJSONTyped,
} from './LinkTypeRead';

/**
 * 
 * @export
 * @interface LinkTypeSingle
 */
export interface LinkTypeSingle {
    /**
     * 
     * @type {LinkTypeRead}
     * @memberof LinkTypeSingle
     */
    data: LinkTypeRead;
}

/**
 * Check if a given object implements the LinkTypeSingle interface.
 */
export function instanceOfLinkTypeSingle(value: object): value is LinkTypeSingle {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function LinkTypeSingleFromJSON(json: any): LinkTypeSingle {
    return LinkTypeSingleFromJSONTyped(json, false);
}

export function LinkTypeSingleFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkTypeSingle {
    if (json == null) {
        return json;
    }
    return {
        
        'data': LinkTypeReadFromJSON(json['data']),
    };
}

export function LinkTypeSingleToJSON(json: any): LinkTypeSingle {
    return LinkTypeSingleToJSONTyped(json, false);
}

export function LinkTypeSingleToJSONTyped(value?: LinkTypeSingle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': LinkTypeReadToJSON(value['data']),
    };
}

