"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfModelConfiguration = instanceOfModelConfiguration;
exports.ModelConfigurationFromJSON = ModelConfigurationFromJSON;
exports.ModelConfigurationFromJSONTyped = ModelConfigurationFromJSONTyped;
exports.ModelConfigurationToJSON = ModelConfigurationToJSON;
exports.ModelConfigurationToJSONTyped = ModelConfigurationToJSONTyped;
const PolymorphicProperty_1 = require("./PolymorphicProperty");
const ConfigValueFilter_1 = require("./ConfigValueFilter");
/**
 * Check if a given object implements the ModelConfiguration interface.
 */
function instanceOfModelConfiguration(value) {
    if (!('title' in value) || value['title'] === undefined)
        return false;
    if (!('value' in value) || value['value'] === undefined)
        return false;
    if (!('editable' in value) || value['editable'] === undefined)
        return false;
    return true;
}
function ModelConfigurationFromJSON(json) {
    return ModelConfigurationFromJSONTyped(json, false);
}
function ModelConfigurationFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'title': (0, ConfigValueFilter_1.ConfigValueFilterFromJSON)(json['title']),
        'value': (0, PolymorphicProperty_1.PolymorphicPropertyFromJSON)(json['value']),
        'editable': json['editable'],
    };
}
function ModelConfigurationToJSON(json) {
    return ModelConfigurationToJSONTyped(json, false);
}
function ModelConfigurationToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'title': (0, ConfigValueFilter_1.ConfigValueFilterToJSON)(value['title']),
        'value': (0, PolymorphicProperty_1.PolymorphicPropertyToJSON)(value['value']),
        'editable': value['editable'],
    };
}
