"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPiggyBankAccountRead = instanceOfPiggyBankAccountRead;
exports.PiggyBankAccountReadFromJSON = PiggyBankAccountReadFromJSON;
exports.PiggyBankAccountReadFromJSONTyped = PiggyBankAccountReadFromJSONTyped;
exports.PiggyBankAccountReadToJSON = PiggyBankAccountReadToJSON;
exports.PiggyBankAccountReadToJSONTyped = PiggyBankAccountReadToJSONTyped;
/**
 * Check if a given object implements the PiggyBankAccountRead interface.
 */
function instanceOfPiggyBankAccountRead(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('currentAmount' in value) || value['currentAmount'] === undefined)
        return false;
    if (!('nativeCurrentAmount' in value) || value['nativeCurrentAmount'] === undefined)
        return false;
    return true;
}
function PiggyBankAccountReadFromJSON(json) {
    return PiggyBankAccountReadFromJSONTyped(json, false);
}
function PiggyBankAccountReadFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'currentAmount': json['current_amount'],
        'nativeCurrentAmount': json['native_current_amount'],
    };
}
function PiggyBankAccountReadToJSON(json) {
    return PiggyBankAccountReadToJSONTyped(json, false);
}
function PiggyBankAccountReadToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'current_amount': value['currentAmount'],
        'native_current_amount': value['nativeCurrentAmount'],
    };
}
