/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PiggyBankRead } from './PiggyBankRead';
import {
    PiggyBankReadFromJSON,
    PiggyBankReadFromJSONTyped,
    PiggyBankReadToJSON,
    PiggyBankReadToJSONTyped,
} from './PiggyBankRead';

/**
 * 
 * @export
 * @interface PiggyBankSingle
 */
export interface PiggyBankSingle {
    /**
     * 
     * @type {PiggyBankRead}
     * @memberof PiggyBankSingle
     */
    data: PiggyBankRead;
}

/**
 * Check if a given object implements the PiggyBankSingle interface.
 */
export function instanceOfPiggyBankSingle(value: object): value is PiggyBankSingle {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PiggyBankSingleFromJSON(json: any): PiggyBankSingle {
    return PiggyBankSingleFromJSONTyped(json, false);
}

export function PiggyBankSingleFromJSONTyped(json: any, ignoreDiscriminator: boolean): PiggyBankSingle {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PiggyBankReadFromJSON(json['data']),
    };
}

export function PiggyBankSingleToJSON(json: any): PiggyBankSingle {
    return PiggyBankSingleToJSONTyped(json, false);
}

export function PiggyBankSingleToJSONTyped(value?: PiggyBankSingle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PiggyBankReadToJSON(value['data']),
    };
}

