/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PiggyBankAccountStore
 */
export interface PiggyBankAccountStore {
    /**
     * The ID of the account.
     * @type {string}
     * @memberof PiggyBankAccountStore
     */
    id: string | null;
    /**
     * The name of the account.
     * @type {string}
     * @memberof PiggyBankAccountStore
     */
    name?: string | null;
    /**
     * The amount saved currently.
     * @type {string}
     * @memberof PiggyBankAccountStore
     */
    currentAmount?: string;
}

/**
 * Check if a given object implements the PiggyBankAccountStore interface.
 */
export function instanceOfPiggyBankAccountStore(value: object): value is PiggyBankAccountStore {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function PiggyBankAccountStoreFromJSON(json: any): PiggyBankAccountStore {
    return PiggyBankAccountStoreFromJSONTyped(json, false);
}

export function PiggyBankAccountStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): PiggyBankAccountStore {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'currentAmount': json['current_amount'] == null ? undefined : json['current_amount'],
    };
}

export function PiggyBankAccountStoreToJSON(json: any): PiggyBankAccountStore {
    return PiggyBankAccountStoreToJSONTyped(json, false);
}

export function PiggyBankAccountStoreToJSONTyped(value?: PiggyBankAccountStore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'current_amount': value['currentAmount'],
    };
}

