"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPiggyBankEvent = instanceOfPiggyBankEvent;
exports.PiggyBankEventFromJSON = PiggyBankEventFromJSON;
exports.PiggyBankEventFromJSONTyped = PiggyBankEventFromJSONTyped;
exports.PiggyBankEventToJSON = PiggyBankEventToJSON;
exports.PiggyBankEventToJSONTyped = PiggyBankEventToJSONTyped;
/**
 * Check if a given object implements the PiggyBankEvent interface.
 */
function instanceOfPiggyBankEvent(value) {
    return true;
}
function PiggyBankEventFromJSON(json) {
    return PiggyBankEventFromJSONTyped(json, false);
}
function PiggyBankEventFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'currencyId': json['currency_id'] == null ? undefined : json['currency_id'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
        'currencySymbol': json['currency_symbol'] == null ? undefined : json['currency_symbol'],
        'currencyDecimalPlaces': json['currency_decimal_places'] == null ? undefined : json['currency_decimal_places'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'transactionJournalId': json['transaction_journal_id'] == null ? undefined : json['transaction_journal_id'],
        'transactionGroupId': json['transaction_group_id'] == null ? undefined : json['transaction_group_id'],
    };
}
function PiggyBankEventToJSON(json) {
    return PiggyBankEventToJSONTyped(json, false);
}
function PiggyBankEventToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'currency_id': value['currencyId'],
        'currency_code': value['currencyCode'],
        'currency_symbol': value['currencySymbol'],
        'currency_decimal_places': value['currencyDecimalPlaces'],
        'amount': value['amount'],
        'transaction_journal_id': value['transactionJournalId'],
        'transaction_group_id': value['transactionGroupId'],
    };
}
