"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPreference = instanceOfPreference;
exports.PreferenceFromJSON = PreferenceFromJSON;
exports.PreferenceFromJSONTyped = PreferenceFromJSONTyped;
exports.PreferenceToJSON = PreferenceToJSON;
exports.PreferenceToJSONTyped = PreferenceToJSONTyped;
const PolymorphicProperty_1 = require("./PolymorphicProperty");
/**
 * Check if a given object implements the Preference interface.
 */
function instanceOfPreference(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('data' in value) || value['data'] === undefined)
        return false;
    return true;
}
function PreferenceFromJSON(json) {
    return PreferenceFromJSONTyped(json, false);
}
function PreferenceFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'name': json['name'],
        'data': (0, PolymorphicProperty_1.PolymorphicPropertyFromJSON)(json['data']),
    };
}
function PreferenceToJSON(json) {
    return PreferenceToJSONTyped(json, false);
}
function PreferenceToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'data': (0, PolymorphicProperty_1.PolymorphicPropertyToJSON)(value['data']),
    };
}
