/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of the repetition. ndom means: the n-th weekday of the month, where you can also specify which day of the week.
 * @export
 */
export const RecurrenceRepetitionType = {
    Daily: 'daily',
    Weekly: 'weekly',
    Ndom: 'ndom',
    Monthly: 'monthly',
    Yearly: 'yearly'
} as const;
export type RecurrenceRepetitionType = typeof RecurrenceRepetitionType[keyof typeof RecurrenceRepetitionType];


export function instanceOfRecurrenceRepetitionType(value: any): boolean {
    for (const key in RecurrenceRepetitionType) {
        if (Object.prototype.hasOwnProperty.call(RecurrenceRepetitionType, key)) {
            if (RecurrenceRepetitionType[key as keyof typeof RecurrenceRepetitionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RecurrenceRepetitionTypeFromJSON(json: any): RecurrenceRepetitionType {
    return RecurrenceRepetitionTypeFromJSONTyped(json, false);
}

export function RecurrenceRepetitionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurrenceRepetitionType {
    return json as RecurrenceRepetitionType;
}

export function RecurrenceRepetitionTypeToJSON(value?: RecurrenceRepetitionType | null): any {
    return value as any;
}

export function RecurrenceRepetitionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): RecurrenceRepetitionType {
    return value as RecurrenceRepetitionType;
}

