"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRecurrenceRepetitionUpdate = instanceOfRecurrenceRepetitionUpdate;
exports.RecurrenceRepetitionUpdateFromJSON = RecurrenceRepetitionUpdateFromJSON;
exports.RecurrenceRepetitionUpdateFromJSONTyped = RecurrenceRepetitionUpdateFromJSONTyped;
exports.RecurrenceRepetitionUpdateToJSON = RecurrenceRepetitionUpdateToJSON;
exports.RecurrenceRepetitionUpdateToJSONTyped = RecurrenceRepetitionUpdateToJSONTyped;
const RecurrenceRepetitionType_1 = require("./RecurrenceRepetitionType");
/**
 * Check if a given object implements the RecurrenceRepetitionUpdate interface.
 */
function instanceOfRecurrenceRepetitionUpdate(value) {
    return true;
}
function RecurrenceRepetitionUpdateFromJSON(json) {
    return RecurrenceRepetitionUpdateFromJSONTyped(json, false);
}
function RecurrenceRepetitionUpdateFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'type': json['type'] == null ? undefined : (0, RecurrenceRepetitionType_1.RecurrenceRepetitionTypeFromJSON)(json['type']),
        'moment': json['moment'] == null ? undefined : json['moment'],
        'skip': json['skip'] == null ? undefined : json['skip'],
        'weekend': json['weekend'] == null ? undefined : json['weekend'],
    };
}
function RecurrenceRepetitionUpdateToJSON(json) {
    return RecurrenceRepetitionUpdateToJSONTyped(json, false);
}
function RecurrenceRepetitionUpdateToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'type': (0, RecurrenceRepetitionType_1.RecurrenceRepetitionTypeToJSON)(value['type']),
        'moment': value['moment'],
        'skip': value['skip'],
        'weekend': value['weekend'],
    };
}
