"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRecurrenceTransaction = instanceOfRecurrenceTransaction;
exports.RecurrenceTransactionFromJSON = RecurrenceTransactionFromJSON;
exports.RecurrenceTransactionFromJSONTyped = RecurrenceTransactionFromJSONTyped;
exports.RecurrenceTransactionToJSON = RecurrenceTransactionToJSON;
exports.RecurrenceTransactionToJSONTyped = RecurrenceTransactionToJSONTyped;
const AccountTypeProperty_1 = require("./AccountTypeProperty");
/**
 * Check if a given object implements the RecurrenceTransaction interface.
 */
function instanceOfRecurrenceTransaction(value) {
    if (!('description' in value) || value['description'] === undefined)
        return false;
    if (!('amount' in value) || value['amount'] === undefined)
        return false;
    return true;
}
function RecurrenceTransactionFromJSON(json) {
    return RecurrenceTransactionFromJSONTyped(json, false);
}
function RecurrenceTransactionFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'description': json['description'],
        'amount': json['amount'],
        'foreignAmount': json['foreign_amount'] == null ? undefined : json['foreign_amount'],
        'currencyId': json['currency_id'] == null ? undefined : json['currency_id'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
        'currencySymbol': json['currency_symbol'] == null ? undefined : json['currency_symbol'],
        'currencyDecimalPlaces': json['currency_decimal_places'] == null ? undefined : json['currency_decimal_places'],
        'foreignCurrencyId': json['foreign_currency_id'] == null ? undefined : json['foreign_currency_id'],
        'foreignCurrencyCode': json['foreign_currency_code'] == null ? undefined : json['foreign_currency_code'],
        'foreignCurrencySymbol': json['foreign_currency_symbol'] == null ? undefined : json['foreign_currency_symbol'],
        'foreignCurrencyDecimalPlaces': json['foreign_currency_decimal_places'] == null ? undefined : json['foreign_currency_decimal_places'],
        'budgetId': json['budget_id'] == null ? undefined : json['budget_id'],
        'budgetName': json['budget_name'] == null ? undefined : json['budget_name'],
        'categoryId': json['category_id'] == null ? undefined : json['category_id'],
        'categoryName': json['category_name'] == null ? undefined : json['category_name'],
        'sourceId': json['source_id'] == null ? undefined : json['source_id'],
        'sourceName': json['source_name'] == null ? undefined : json['source_name'],
        'sourceIban': json['source_iban'] == null ? undefined : json['source_iban'],
        'sourceType': json['source_type'] == null ? undefined : (0, AccountTypeProperty_1.AccountTypePropertyFromJSON)(json['source_type']),
        'destinationId': json['destination_id'] == null ? undefined : json['destination_id'],
        'destinationName': json['destination_name'] == null ? undefined : json['destination_name'],
        'destinationIban': json['destination_iban'] == null ? undefined : json['destination_iban'],
        'destinationType': json['destination_type'] == null ? undefined : (0, AccountTypeProperty_1.AccountTypePropertyFromJSON)(json['destination_type']),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'piggyBankId': json['piggy_bank_id'] == null ? undefined : json['piggy_bank_id'],
        'piggyBankName': json['piggy_bank_name'] == null ? undefined : json['piggy_bank_name'],
        'billId': json['bill_id'] == null ? undefined : json['bill_id'],
        'billName': json['bill_name'] == null ? undefined : json['bill_name'],
    };
}
function RecurrenceTransactionToJSON(json) {
    return RecurrenceTransactionToJSONTyped(json, false);
}
function RecurrenceTransactionToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'description': value['description'],
        'amount': value['amount'],
        'foreign_amount': value['foreignAmount'],
        'currency_id': value['currencyId'],
        'currency_code': value['currencyCode'],
        'foreign_currency_id': value['foreignCurrencyId'],
        'foreign_currency_code': value['foreignCurrencyCode'],
        'budget_id': value['budgetId'],
        'category_id': value['categoryId'],
        'category_name': value['categoryName'],
        'source_id': value['sourceId'],
        'source_name': value['sourceName'],
        'source_type': (0, AccountTypeProperty_1.AccountTypePropertyToJSON)(value['sourceType']),
        'destination_id': value['destinationId'],
        'destination_name': value['destinationName'],
        'destination_type': (0, AccountTypeProperty_1.AccountTypePropertyToJSON)(value['destinationType']),
        'tags': value['tags'],
        'piggy_bank_id': value['piggyBankId'],
        'piggy_bank_name': value['piggyBankName'],
        'bill_id': value['billId'],
        'bill_name': value['billName'],
    };
}
