"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRecurrenceUpdate = instanceOfRecurrenceUpdate;
exports.RecurrenceUpdateFromJSON = RecurrenceUpdateFromJSON;
exports.RecurrenceUpdateFromJSONTyped = RecurrenceUpdateFromJSONTyped;
exports.RecurrenceUpdateToJSON = RecurrenceUpdateToJSON;
exports.RecurrenceUpdateToJSONTyped = RecurrenceUpdateToJSONTyped;
const RecurrenceTransactionUpdate_1 = require("./RecurrenceTransactionUpdate");
const RecurrenceRepetitionUpdate_1 = require("./RecurrenceRepetitionUpdate");
/**
 * Check if a given object implements the RecurrenceUpdate interface.
 */
function instanceOfRecurrenceUpdate(value) {
    return true;
}
function RecurrenceUpdateFromJSON(json) {
    return RecurrenceUpdateFromJSONTyped(json, false);
}
function RecurrenceUpdateFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'firstDate': json['first_date'] == null ? undefined : (new Date(json['first_date'])),
        'repeatUntil': json['repeat_until'] == null ? undefined : (new Date(json['repeat_until'])),
        'nrOfRepetitions': json['nr_of_repetitions'] == null ? undefined : json['nr_of_repetitions'],
        'applyRules': json['apply_rules'] == null ? undefined : json['apply_rules'],
        'active': json['active'] == null ? undefined : json['active'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'repetitions': json['repetitions'] == null ? undefined : (json['repetitions'].map(RecurrenceRepetitionUpdate_1.RecurrenceRepetitionUpdateFromJSON)),
        'transactions': json['transactions'] == null ? undefined : (json['transactions'].map(RecurrenceTransactionUpdate_1.RecurrenceTransactionUpdateFromJSON)),
    };
}
function RecurrenceUpdateToJSON(json) {
    return RecurrenceUpdateToJSONTyped(json, false);
}
function RecurrenceUpdateToJSONTyped(value, ignoreDiscriminator = false) {
    var _a;
    if (value == null) {
        return value;
    }
    return {
        'title': value['title'],
        'description': value['description'],
        'first_date': value['firstDate'] == null ? undefined : ((value['firstDate']).toISOString().substring(0, 10)),
        'repeat_until': value['repeatUntil'] === null ? null : ((_a = value['repeatUntil']) === null || _a === void 0 ? void 0 : _a.toISOString().substring(0, 10)),
        'nr_of_repetitions': value['nrOfRepetitions'],
        'apply_rules': value['applyRules'],
        'active': value['active'],
        'notes': value['notes'],
        'repetitions': value['repetitions'] == null ? undefined : (value['repetitions'].map(RecurrenceRepetitionUpdate_1.RecurrenceRepetitionUpdateToJSON)),
        'transactions': value['transactions'] == null ? undefined : (value['transactions'].map(RecurrenceTransactionUpdate_1.RecurrenceTransactionUpdateToJSON)),
    };
}
