/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecurrenceTransactionUpdate } from './RecurrenceTransactionUpdate';
import {
    RecurrenceTransactionUpdateFromJSON,
    RecurrenceTransactionUpdateFromJSONTyped,
    RecurrenceTransactionUpdateToJSON,
    RecurrenceTransactionUpdateToJSONTyped,
} from './RecurrenceTransactionUpdate';
import type { RecurrenceRepetitionUpdate } from './RecurrenceRepetitionUpdate';
import {
    RecurrenceRepetitionUpdateFromJSON,
    RecurrenceRepetitionUpdateFromJSONTyped,
    RecurrenceRepetitionUpdateToJSON,
    RecurrenceRepetitionUpdateToJSONTyped,
} from './RecurrenceRepetitionUpdate';

/**
 * 
 * @export
 * @interface RecurrenceUpdate
 */
export interface RecurrenceUpdate {
    /**
     * 
     * @type {string}
     * @memberof RecurrenceUpdate
     */
    title?: string;
    /**
     * Not to be confused with the description of the actual transaction(s) being created.
     * @type {string}
     * @memberof RecurrenceUpdate
     */
    description?: string;
    /**
     * First time the recurring transaction will fire.
     * @type {Date}
     * @memberof RecurrenceUpdate
     */
    firstDate?: Date;
    /**
     * Date until the recurring transaction can fire. After that date, it's basically inactive. Use either this field or repetitions.
     * @type {Date}
     * @memberof RecurrenceUpdate
     */
    repeatUntil?: Date | null;
    /**
     * Max number of created transactions. Use either this field or repeat_until.
     * @type {number}
     * @memberof RecurrenceUpdate
     */
    nrOfRepetitions?: number | null;
    /**
     * Whether or not to fire the rules after the creation of a transaction.
     * @type {boolean}
     * @memberof RecurrenceUpdate
     */
    applyRules?: boolean;
    /**
     * If the recurrence is even active.
     * @type {boolean}
     * @memberof RecurrenceUpdate
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RecurrenceUpdate
     */
    notes?: string | null;
    /**
     * 
     * @type {Array<RecurrenceRepetitionUpdate>}
     * @memberof RecurrenceUpdate
     */
    repetitions?: Array<RecurrenceRepetitionUpdate>;
    /**
     * 
     * @type {Array<RecurrenceTransactionUpdate>}
     * @memberof RecurrenceUpdate
     */
    transactions?: Array<RecurrenceTransactionUpdate>;
}

/**
 * Check if a given object implements the RecurrenceUpdate interface.
 */
export function instanceOfRecurrenceUpdate(value: object): value is RecurrenceUpdate {
    return true;
}

export function RecurrenceUpdateFromJSON(json: any): RecurrenceUpdate {
    return RecurrenceUpdateFromJSONTyped(json, false);
}

export function RecurrenceUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurrenceUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'firstDate': json['first_date'] == null ? undefined : (new Date(json['first_date'])),
        'repeatUntil': json['repeat_until'] == null ? undefined : (new Date(json['repeat_until'])),
        'nrOfRepetitions': json['nr_of_repetitions'] == null ? undefined : json['nr_of_repetitions'],
        'applyRules': json['apply_rules'] == null ? undefined : json['apply_rules'],
        'active': json['active'] == null ? undefined : json['active'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'repetitions': json['repetitions'] == null ? undefined : ((json['repetitions'] as Array<any>).map(RecurrenceRepetitionUpdateFromJSON)),
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(RecurrenceTransactionUpdateFromJSON)),
    };
}

export function RecurrenceUpdateToJSON(json: any): RecurrenceUpdate {
    return RecurrenceUpdateToJSONTyped(json, false);
}

export function RecurrenceUpdateToJSONTyped(value?: RecurrenceUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'first_date': value['firstDate'] == null ? undefined : ((value['firstDate']).toISOString().substring(0,10)),
        'repeat_until': value['repeatUntil'] === null ? null : ((value['repeatUntil'] as any)?.toISOString().substring(0,10)),
        'nr_of_repetitions': value['nrOfRepetitions'],
        'apply_rules': value['applyRules'],
        'active': value['active'],
        'notes': value['notes'],
        'repetitions': value['repetitions'] == null ? undefined : ((value['repetitions'] as Array<any>).map(RecurrenceRepetitionUpdateToJSON)),
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(RecurrenceTransactionUpdateToJSON)),
    };
}

