"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRule = instanceOfRule;
exports.RuleFromJSON = RuleFromJSON;
exports.RuleFromJSONTyped = RuleFromJSONTyped;
exports.RuleToJSON = RuleToJSON;
exports.RuleToJSONTyped = RuleToJSONTyped;
const RuleTriggerType_1 = require("./RuleTriggerType");
const RuleAction_1 = require("./RuleAction");
const RuleTrigger_1 = require("./RuleTrigger");
/**
 * Check if a given object implements the Rule interface.
 */
function instanceOfRule(value) {
    if (!('title' in value) || value['title'] === undefined)
        return false;
    if (!('ruleGroupId' in value) || value['ruleGroupId'] === undefined)
        return false;
    if (!('trigger' in value) || value['trigger'] === undefined)
        return false;
    if (!('triggers' in value) || value['triggers'] === undefined)
        return false;
    if (!('actions' in value) || value['actions'] === undefined)
        return false;
    return true;
}
function RuleFromJSON(json) {
    return RuleFromJSONTyped(json, false);
}
function RuleFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'ruleGroupId': json['rule_group_id'],
        'ruleGroupTitle': json['rule_group_title'] == null ? undefined : json['rule_group_title'],
        'order': json['order'] == null ? undefined : json['order'],
        'trigger': (0, RuleTriggerType_1.RuleTriggerTypeFromJSON)(json['trigger']),
        'active': json['active'] == null ? undefined : json['active'],
        'strict': json['strict'] == null ? undefined : json['strict'],
        'stopProcessing': json['stop_processing'] == null ? undefined : json['stop_processing'],
        'triggers': (json['triggers'].map(RuleTrigger_1.RuleTriggerFromJSON)),
        'actions': (json['actions'].map(RuleAction_1.RuleActionFromJSON)),
    };
}
function RuleToJSON(json) {
    return RuleToJSONTyped(json, false);
}
function RuleToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'title': value['title'],
        'description': value['description'],
        'rule_group_id': value['ruleGroupId'],
        'rule_group_title': value['ruleGroupTitle'],
        'trigger': (0, RuleTriggerType_1.RuleTriggerTypeToJSON)(value['trigger']),
        'active': value['active'],
        'strict': value['strict'],
        'stop_processing': value['stopProcessing'],
        'triggers': (value['triggers'].map(RuleTrigger_1.RuleTriggerToJSON)),
        'actions': (value['actions'].map(RuleAction_1.RuleActionToJSON)),
    };
}
