"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RuleActionKeyword = void 0;
exports.instanceOfRuleActionKeyword = instanceOfRuleActionKeyword;
exports.RuleActionKeywordFromJSON = RuleActionKeywordFromJSON;
exports.RuleActionKeywordFromJSONTyped = RuleActionKeywordFromJSONTyped;
exports.RuleActionKeywordToJSON = RuleActionKeywordToJSON;
exports.RuleActionKeywordToJSONTyped = RuleActionKeywordToJSONTyped;
/**
 * The type of thing this action will do. A limited set is possible.
 * @export
 */
exports.RuleActionKeyword = {
    UserAction: 'user_action',
    SetCategory: 'set_category',
    ClearCategory: 'clear_category',
    SetBudget: 'set_budget',
    ClearBudget: 'clear_budget',
    AddTag: 'add_tag',
    RemoveTag: 'remove_tag',
    RemoveAllTags: 'remove_all_tags',
    SetDescription: 'set_description',
    AppendDescription: 'append_description',
    PrependDescription: 'prepend_description',
    SetSourceAccount: 'set_source_account',
    SetDestinationAccount: 'set_destination_account',
    SetNotes: 'set_notes',
    AppendNotes: 'append_notes',
    PrependNotes: 'prepend_notes',
    ClearNotes: 'clear_notes',
    LinkToBill: 'link_to_bill',
    ConvertWithdrawal: 'convert_withdrawal',
    ConvertDeposit: 'convert_deposit',
    ConvertTransfer: 'convert_transfer',
    DeleteTransaction: 'delete_transaction'
};
function instanceOfRuleActionKeyword(value) {
    for (const key in exports.RuleActionKeyword) {
        if (Object.prototype.hasOwnProperty.call(exports.RuleActionKeyword, key)) {
            if (exports.RuleActionKeyword[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function RuleActionKeywordFromJSON(json) {
    return RuleActionKeywordFromJSONTyped(json, false);
}
function RuleActionKeywordFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function RuleActionKeywordToJSON(value) {
    return value;
}
function RuleActionKeywordToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
