"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RuleTriggerType = void 0;
exports.instanceOfRuleTriggerType = instanceOfRuleTriggerType;
exports.RuleTriggerTypeFromJSON = RuleTriggerTypeFromJSON;
exports.RuleTriggerTypeFromJSONTyped = RuleTriggerTypeFromJSONTyped;
exports.RuleTriggerTypeToJSON = RuleTriggerTypeToJSON;
exports.RuleTriggerTypeToJSONTyped = RuleTriggerTypeToJSONTyped;
/**
 * Which action is necessary for the rule to fire? Use either store-journal or update-journal.
 * @export
 */
exports.RuleTriggerType = {
    StoreJournal: 'store-journal',
    UpdateJournal: 'update-journal'
};
function instanceOfRuleTriggerType(value) {
    for (const key in exports.RuleTriggerType) {
        if (Object.prototype.hasOwnProperty.call(exports.RuleTriggerType, key)) {
            if (exports.RuleTriggerType[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function RuleTriggerTypeFromJSON(json) {
    return RuleTriggerTypeFromJSONTyped(json, false);
}
function RuleTriggerTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function RuleTriggerTypeToJSON(value) {
    return value;
}
function RuleTriggerTypeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
