"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfRuleGroupStore = instanceOfRuleGroupStore;
exports.RuleGroupStoreFromJSON = RuleGroupStoreFromJSON;
exports.RuleGroupStoreFromJSONTyped = RuleGroupStoreFromJSONTyped;
exports.RuleGroupStoreToJSON = RuleGroupStoreToJSON;
exports.RuleGroupStoreToJSONTyped = RuleGroupStoreToJSONTyped;
/**
 * Check if a given object implements the RuleGroupStore interface.
 */
function instanceOfRuleGroupStore(value) {
    if (!('title' in value) || value['title'] === undefined)
        return false;
    return true;
}
function RuleGroupStoreFromJSON(json) {
    return RuleGroupStoreFromJSONTyped(json, false);
}
function RuleGroupStoreFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'order': json['order'] == null ? undefined : json['order'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}
function RuleGroupStoreToJSON(json) {
    return RuleGroupStoreToJSONTyped(json, false);
}
function RuleGroupStoreToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'title': value['title'],
        'description': value['description'],
        'order': value['order'],
        'active': value['active'],
    };
}
