/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Can only be one one these account types. import, initial-balance and reconciliation cannot be set manually.
 * @export
 */
export const ShortAccountTypeProperty = {
    Asset: 'asset',
    Expense: 'expense',
    Import: 'import',
    Revenue: 'revenue',
    Cash: 'cash',
    Liability: 'liability',
    Liabilities: 'liabilities',
    InitialBalance: 'initial-balance',
    Reconciliation: 'reconciliation'
} as const;
export type ShortAccountTypeProperty = typeof ShortAccountTypeProperty[keyof typeof ShortAccountTypeProperty];


export function instanceOfShortAccountTypeProperty(value: any): boolean {
    for (const key in ShortAccountTypeProperty) {
        if (Object.prototype.hasOwnProperty.call(ShortAccountTypeProperty, key)) {
            if (ShortAccountTypeProperty[key as keyof typeof ShortAccountTypeProperty] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ShortAccountTypePropertyFromJSON(json: any): ShortAccountTypeProperty {
    return ShortAccountTypePropertyFromJSONTyped(json, false);
}

export function ShortAccountTypePropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShortAccountTypeProperty {
    return json as ShortAccountTypeProperty;
}

export function ShortAccountTypePropertyToJSON(value?: ShortAccountTypeProperty | null): any {
    return value as any;
}

export function ShortAccountTypePropertyToJSONTyped(value: any, ignoreDiscriminator: boolean): ShortAccountTypeProperty {
    return value as ShortAccountTypeProperty;
}

