"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSystemInfo = instanceOfSystemInfo;
exports.SystemInfoFromJSON = SystemInfoFromJSON;
exports.SystemInfoFromJSONTyped = SystemInfoFromJSONTyped;
exports.SystemInfoToJSON = SystemInfoToJSON;
exports.SystemInfoToJSONTyped = SystemInfoToJSONTyped;
const SystemInfoData_1 = require("./SystemInfoData");
/**
 * Check if a given object implements the SystemInfo interface.
 */
function instanceOfSystemInfo(value) {
    return true;
}
function SystemInfoFromJSON(json) {
    return SystemInfoFromJSONTyped(json, false);
}
function SystemInfoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'data': json['data'] == null ? undefined : (0, SystemInfoData_1.SystemInfoDataFromJSON)(json['data']),
    };
}
function SystemInfoToJSON(json) {
    return SystemInfoToJSONTyped(json, false);
}
function SystemInfoToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'data': (0, SystemInfoData_1.SystemInfoDataToJSON)(value['data']),
    };
}
