"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfTransactionStore = instanceOfTransactionStore;
exports.TransactionStoreFromJSON = TransactionStoreFromJSON;
exports.TransactionStoreFromJSONTyped = TransactionStoreFromJSONTyped;
exports.TransactionStoreToJSON = TransactionStoreToJSON;
exports.TransactionStoreToJSONTyped = TransactionStoreToJSONTyped;
const TransactionSplitStore_1 = require("./TransactionSplitStore");
/**
 * Check if a given object implements the TransactionStore interface.
 */
function instanceOfTransactionStore(value) {
    if (!('transactions' in value) || value['transactions'] === undefined)
        return false;
    return true;
}
function TransactionStoreFromJSON(json) {
    return TransactionStoreFromJSONTyped(json, false);
}
function TransactionStoreFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'errorIfDuplicateHash': json['error_if_duplicate_hash'] == null ? undefined : json['error_if_duplicate_hash'],
        'applyRules': json['apply_rules'] == null ? undefined : json['apply_rules'],
        'fireWebhooks': json['fire_webhooks'] == null ? undefined : json['fire_webhooks'],
        'groupTitle': json['group_title'] == null ? undefined : json['group_title'],
        'transactions': (json['transactions'].map(TransactionSplitStore_1.TransactionSplitStoreFromJSON)),
    };
}
function TransactionStoreToJSON(json) {
    return TransactionStoreToJSONTyped(json, false);
}
function TransactionStoreToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'error_if_duplicate_hash': value['errorIfDuplicateHash'],
        'apply_rules': value['applyRules'],
        'fire_webhooks': value['fireWebhooks'],
        'group_title': value['groupTitle'],
        'transactions': (value['transactions'].map(TransactionSplitStore_1.TransactionSplitStoreToJSON)),
    };
}
