/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TransactionTypeFilter = {
    All: 'all',
    Withdrawal: 'withdrawal',
    Withdrawals: 'withdrawals',
    Expense: 'expense',
    Deposit: 'deposit',
    Deposits: 'deposits',
    Income: 'income',
    Transfer: 'transfer',
    Transfers: 'transfers',
    OpeningBalance: 'opening_balance',
    Reconciliation: 'reconciliation',
    Special: 'special',
    Specials: 'specials',
    Default: 'default'
} as const;
export type TransactionTypeFilter = typeof TransactionTypeFilter[keyof typeof TransactionTypeFilter];


export function instanceOfTransactionTypeFilter(value: any): boolean {
    for (const key in TransactionTypeFilter) {
        if (Object.prototype.hasOwnProperty.call(TransactionTypeFilter, key)) {
            if (TransactionTypeFilter[key as keyof typeof TransactionTypeFilter] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TransactionTypeFilterFromJSON(json: any): TransactionTypeFilter {
    return TransactionTypeFilterFromJSONTyped(json, false);
}

export function TransactionTypeFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionTypeFilter {
    return json as TransactionTypeFilter;
}

export function TransactionTypeFilterToJSON(value?: TransactionTypeFilter | null): any {
    return value as any;
}

export function TransactionTypeFilterToJSONTyped(value: any, ignoreDiscriminator: boolean): TransactionTypeFilter {
    return value as TransactionTypeFilter;
}

