"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfTransaction = instanceOfTransaction;
exports.TransactionFromJSON = TransactionFromJSON;
exports.TransactionFromJSONTyped = TransactionFromJSONTyped;
exports.TransactionToJSON = TransactionToJSON;
exports.TransactionToJSONTyped = TransactionToJSONTyped;
const TransactionSplit_1 = require("./TransactionSplit");
/**
 * Check if a given object implements the Transaction interface.
 */
function instanceOfTransaction(value) {
    if (!('transactions' in value) || value['transactions'] === undefined)
        return false;
    return true;
}
function TransactionFromJSON(json) {
    return TransactionFromJSONTyped(json, false);
}
function TransactionFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'user': json['user'] == null ? undefined : json['user'],
        'groupTitle': json['group_title'] == null ? undefined : json['group_title'],
        'transactions': (json['transactions'].map(TransactionSplit_1.TransactionSplitFromJSON)),
    };
}
function TransactionToJSON(json) {
    return TransactionToJSONTyped(json, false);
}
function TransactionToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'group_title': value['groupTitle'],
        'transactions': (value['transactions'].map(TransactionSplit_1.TransactionSplitToJSON)),
    };
}
