"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUserGroupReadAttributes = instanceOfUserGroupReadAttributes;
exports.UserGroupReadAttributesFromJSON = UserGroupReadAttributesFromJSON;
exports.UserGroupReadAttributesFromJSONTyped = UserGroupReadAttributesFromJSONTyped;
exports.UserGroupReadAttributesToJSON = UserGroupReadAttributesToJSON;
exports.UserGroupReadAttributesToJSONTyped = UserGroupReadAttributesToJSONTyped;
const UserGroupReadMembers_1 = require("./UserGroupReadMembers");
/**
 * Check if a given object implements the UserGroupReadAttributes interface.
 */
function instanceOfUserGroupReadAttributes(value) {
    return true;
}
function UserGroupReadAttributesFromJSON(json) {
    return UserGroupReadAttributesFromJSONTyped(json, false);
}
function UserGroupReadAttributesFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'inUse': json['in_use'] == null ? undefined : json['in_use'],
        'canSeeMembers': json['can_see_members'] == null ? undefined : json['can_see_members'],
        'title': json['title'] == null ? undefined : json['title'],
        'nativeCurrencyId': json['native_currency_id'] == null ? undefined : json['native_currency_id'],
        'nativeCurrencyCode': json['native_currency_code'] == null ? undefined : json['native_currency_code'],
        'nativeCurrencySymbol': json['native_currency_symbol'] == null ? undefined : json['native_currency_symbol'],
        'nativeCurrencyDecimalPlaces': json['native_currency_decimal_places'] == null ? undefined : json['native_currency_decimal_places'],
        'members': json['members'] == null ? undefined : (json['members'].map(UserGroupReadMembers_1.UserGroupReadMembersFromJSON)),
    };
}
function UserGroupReadAttributesToJSON(json) {
    return UserGroupReadAttributesToJSONTyped(json, false);
}
function UserGroupReadAttributesToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'title': value['title'],
        'native_currency_code': value['nativeCurrencyCode'],
        'members': value['members'] == null ? undefined : (value['members'].map(UserGroupReadMembers_1.UserGroupReadMembersToJSON)),
    };
}
