"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUserGroupReadMembers = instanceOfUserGroupReadMembers;
exports.UserGroupReadMembersFromJSON = UserGroupReadMembersFromJSON;
exports.UserGroupReadMembersFromJSONTyped = UserGroupReadMembersFromJSONTyped;
exports.UserGroupReadMembersToJSON = UserGroupReadMembersToJSON;
exports.UserGroupReadMembersToJSONTyped = UserGroupReadMembersToJSONTyped;
const UserGroupReadRole_1 = require("./UserGroupReadRole");
/**
 * Check if a given object implements the UserGroupReadMembers interface.
 */
function instanceOfUserGroupReadMembers(value) {
    return true;
}
function UserGroupReadMembersFromJSON(json) {
    return UserGroupReadMembersFromJSONTyped(json, false);
}
function UserGroupReadMembersFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'userEmail': json['user_email'] == null ? undefined : json['user_email'],
        'you': json['you'] == null ? undefined : json['you'],
        'roles': json['roles'] == null ? undefined : (new Set(json['roles'].map(UserGroupReadRole_1.UserGroupReadRoleFromJSON))),
    };
}
function UserGroupReadMembersToJSON(json) {
    return UserGroupReadMembersToJSONTyped(json, false);
}
function UserGroupReadMembersToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'roles': value['roles'] == null ? undefined : (Array.from(value['roles']).map(UserGroupReadRole_1.UserGroupReadRoleToJSON)),
    };
}
