/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserGroupUpdate
 */
export interface UserGroupUpdate {
    /**
     * A descriptive title for the user group.
     * @type {string}
     * @memberof UserGroupUpdate
     */
    title: string;
    /**
     * Use either native_currency_id or native_currency_code. This will set the native currency for the user group ('financial administration').
     * @type {string}
     * @memberof UserGroupUpdate
     */
    nativeCurrencyId?: string;
    /**
     * Use either native_currency_id or native_currency_code. This will set the native currency for the user group ('financial administration').
     * @type {string}
     * @memberof UserGroupUpdate
     */
    nativeCurrencyCode?: string;
}

/**
 * Check if a given object implements the UserGroupUpdate interface.
 */
export function instanceOfUserGroupUpdate(value: object): value is UserGroupUpdate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function UserGroupUpdateFromJSON(json: any): UserGroupUpdate {
    return UserGroupUpdateFromJSONTyped(json, false);
}

export function UserGroupUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGroupUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'nativeCurrencyId': json['native_currency_id'] == null ? undefined : json['native_currency_id'],
        'nativeCurrencyCode': json['native_currency_code'] == null ? undefined : json['native_currency_code'],
    };
}

export function UserGroupUpdateToJSON(json: any): UserGroupUpdate {
    return UserGroupUpdateToJSONTyped(json, false);
}

export function UserGroupUpdateToJSONTyped(value?: UserGroupUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'native_currency_id': value['nativeCurrencyId'],
        'native_currency_code': value['nativeCurrencyCode'],
    };
}

