"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUserGroupSingle = instanceOfUserGroupSingle;
exports.UserGroupSingleFromJSON = UserGroupSingleFromJSON;
exports.UserGroupSingleFromJSONTyped = UserGroupSingleFromJSONTyped;
exports.UserGroupSingleToJSON = UserGroupSingleToJSON;
exports.UserGroupSingleToJSONTyped = UserGroupSingleToJSONTyped;
const UserGroupRead_1 = require("./UserGroupRead");
/**
 * Check if a given object implements the UserGroupSingle interface.
 */
function instanceOfUserGroupSingle(value) {
    if (!('data' in value) || value['data'] === undefined)
        return false;
    return true;
}
function UserGroupSingleFromJSON(json) {
    return UserGroupSingleFromJSONTyped(json, false);
}
function UserGroupSingleFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'data': (0, UserGroupRead_1.UserGroupReadFromJSON)(json['data']),
    };
}
function UserGroupSingleToJSON(json) {
    return UserGroupSingleToJSONTyped(json, false);
}
function UserGroupSingleToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'data': (0, UserGroupRead_1.UserGroupReadToJSON)(value['data']),
    };
}
