"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebhookResponse = void 0;
exports.instanceOfWebhookResponse = instanceOfWebhookResponse;
exports.WebhookResponseFromJSON = WebhookResponseFromJSON;
exports.WebhookResponseFromJSONTyped = WebhookResponseFromJSONTyped;
exports.WebhookResponseToJSON = WebhookResponseToJSON;
exports.WebhookResponseToJSONTyped = WebhookResponseToJSONTyped;
/**
 * Indicator for what Firefly III will deliver to the webhook URL.
 * @export
 */
exports.WebhookResponse = {
    Transactions: 'TRANSACTIONS',
    Accounts: 'ACCOUNTS',
    None: 'NONE'
};
function instanceOfWebhookResponse(value) {
    for (const key in exports.WebhookResponse) {
        if (Object.prototype.hasOwnProperty.call(exports.WebhookResponse, key)) {
            if (exports.WebhookResponse[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function WebhookResponseFromJSON(json) {
    return WebhookResponseFromJSONTyped(json, false);
}
function WebhookResponseFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function WebhookResponseToJSON(value) {
    return value;
}
function WebhookResponseToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
