"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfWebhookStore = instanceOfWebhookStore;
exports.WebhookStoreFromJSON = WebhookStoreFromJSON;
exports.WebhookStoreFromJSONTyped = WebhookStoreFromJSONTyped;
exports.WebhookStoreToJSON = WebhookStoreToJSON;
exports.WebhookStoreToJSONTyped = WebhookStoreToJSONTyped;
const WebhookTrigger_1 = require("./WebhookTrigger");
const WebhookResponse_1 = require("./WebhookResponse");
const WebhookDelivery_1 = require("./WebhookDelivery");
/**
 * Check if a given object implements the WebhookStore interface.
 */
function instanceOfWebhookStore(value) {
    if (!('title' in value) || value['title'] === undefined)
        return false;
    if (!('trigger' in value) || value['trigger'] === undefined)
        return false;
    if (!('response' in value) || value['response'] === undefined)
        return false;
    if (!('delivery' in value) || value['delivery'] === undefined)
        return false;
    if (!('url' in value) || value['url'] === undefined)
        return false;
    return true;
}
function WebhookStoreFromJSON(json) {
    return WebhookStoreFromJSONTyped(json, false);
}
function WebhookStoreFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'active': json['active'] == null ? undefined : json['active'],
        'title': json['title'],
        'trigger': (0, WebhookTrigger_1.WebhookTriggerFromJSON)(json['trigger']),
        'response': (0, WebhookResponse_1.WebhookResponseFromJSON)(json['response']),
        'delivery': (0, WebhookDelivery_1.WebhookDeliveryFromJSON)(json['delivery']),
        'url': json['url'],
    };
}
function WebhookStoreToJSON(json) {
    return WebhookStoreToJSONTyped(json, false);
}
function WebhookStoreToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'active': value['active'],
        'title': value['title'],
        'trigger': (0, WebhookTrigger_1.WebhookTriggerToJSON)(value['trigger']),
        'response': (0, WebhookResponse_1.WebhookResponseToJSON)(value['response']),
        'delivery': (0, WebhookDelivery_1.WebhookDeliveryToJSON)(value['delivery']),
        'url': value['url'],
    };
}
