"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v6.2.21
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-07-18T05:50:30+00:00 Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * The version of the OpenAPI document: v6.2.21
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfWebhookRead = instanceOfWebhookRead;
exports.WebhookReadFromJSON = WebhookReadFromJSON;
exports.WebhookReadFromJSONTyped = WebhookReadFromJSONTyped;
exports.WebhookReadToJSON = WebhookReadToJSON;
exports.WebhookReadToJSONTyped = WebhookReadToJSONTyped;
const Webhook_1 = require("./Webhook");
const ObjectLink_1 = require("./ObjectLink");
/**
 * Check if a given object implements the WebhookRead interface.
 */
function instanceOfWebhookRead(value) {
    if (!('type' in value) || value['type'] === undefined)
        return false;
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('attributes' in value) || value['attributes'] === undefined)
        return false;
    if (!('links' in value) || value['links'] === undefined)
        return false;
    return true;
}
function WebhookReadFromJSON(json) {
    return WebhookReadFromJSONTyped(json, false);
}
function WebhookReadFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'type': json['type'],
        'id': json['id'],
        'attributes': (0, Webhook_1.WebhookFromJSON)(json['attributes']),
        'links': (0, ObjectLink_1.ObjectLinkFromJSON)(json['links']),
    };
}
function WebhookReadToJSON(json) {
    return WebhookReadToJSONTyped(json, false);
}
function WebhookReadToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'type': value['type'],
        'id': value['id'],
        'attributes': (0, Webhook_1.WebhookToJSON)(value['attributes']),
        'links': (0, ObjectLink_1.ObjectLinkToJSON)(value['links']),
    };
}
